### ISSUE TITLE
JSONDecodeError 

### ISSUE THREAD

**Issue by noenic** [mroelandts/pyhomebridge#2]
When I start my code I get the following error :

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 I don't know from where it comes since my homebridge starts in insecure mode and it's the good parameters in the function call

controller = HomeBridgeController(host="127.0.0.1", port=8581, auth="543-78-478")

Do you know how to fix this thanks?  :)

**Comment by mroelandts** [comment]
Can you give me more info please?

Which version of homebridge are you using?
I guess you're using python3?
Are you using the `control-homebridge.py` script or the python lib yourself?
More logging or output?

**Comment by noenic** [comment]
> Can you give me more info please?
> 
> 
> 
> Which version of homebridge are you using?
> 
> I guess you're using python3?
> 
> Are you using the `control-homebridge.py` script or the python lib yourself?
> 
> More logging or output?

Am using the python lib and using Python 3. 
For the Homebridge version It might be the problem since I can't update it... everytime I try to run the updates command it load but after the required restart nothing changes ... It is 1.1.6.

**Comment by noenic** [comment]
> 
> 
> Can you give me more info please?
> 
> Which version of homebridge are you using?
> I guess you're using python3?
> Are you using the `control-homebridge.py` script or the python lib yourself?
> More logging or output?


Hi again, since I couldn't update Homebridge I completely reinstalled it, now I'm at the latest version but I still have the same error... Here is the Full Traceback error:

_Traceback (most recent call last):_
  File "C:\Users\noenic\Desktop\Nouveau document texte.py", line 3, in <module>
    controller = HomeBridgeController(host="192.168.1.173", port=8581, auth="915-34-310")
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\site-packages\homebridge\__init__.py", line 62, in __init__
    if self._get_accessories() is False:
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\site-packages\homebridge\__init__.py", line 78, in _get_accessories
    for accessory in get_response.json()['accessories']:
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\noenic\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)




EDIT : **MY BAD**  Am just a complete idiot...used the UI port, better use the HAP port silly mistake sorry...
